sheets:
  IFB1.2018.15:
    input_cells:
      face_value: C22
      date: C10
    output_range: ''
  IFB1.2023.17:
    input_cells:
      face_value: C23
      date: C11
    output_range: ''
  IFB1.2023.07:
    input_cells:
      face_value: C22
      date: C10
    output_range: ''
  IFB1.2023.6.5:
    input_cells:
      face_value: D23
      date: D11
    output_range: ''
  IFB1.2024.8.5:
    input_cells:
      face_value: C22
      date: C10
    output_range: ''
